server:
  servlet:
    context-path: /api

spring:
  application:
    name: fitness-application
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/dodera
    username: george
    password: george
    driver-class-name: com.mysql.cj.jdbc.Driver
      #spring.jpa.show-sql: true
  mail:
    host: smtp.hostinger.com
    port: 465
    username: test@doderasoft.com
    password: DoderaTest123*
    properties:
      mail:
        smtp:
          auth: true
          ssl: true
          starttls: true

security:
  ignored=/**:

stripe:
  api:
    token: "${STRIPE_API_KEY}"
  webhook:
    token: "${STRIPE_WEBHOOK_SECRET}"

fitness:
  token:
    jwt-signing-key: "${JWT_SIGNING_KEY}"
    expiration-time: 86400
